/* DEFINE_IDTYPE(index, idtype, str, wstr, ids, prefix) */
DEFINE_IDTYPE( 0, IDTYPE_UNKNOWN    , "Unknown.ID"      , L"Unknown.ID"     , IDS_UNKNOWN_ID    , L""       )
DEFINE_IDTYPE( 1, IDTYPE_CURSOR     , "Cursor.ID"       , L"Cursor.ID"      , IDS_CURSOR_ID     , L"IDC_"   )
DEFINE_IDTYPE( 2, IDTYPE_BITMAP     , "Bitmap.ID"       , L"Bitmap.ID"      , IDS_BITMAP_ID     , L"IDB_"   )
DEFINE_IDTYPE( 3, IDTYPE_MENU       , "Menu.ID"         , L"Menu.ID"        , IDS_MENU_ID       , L"IDR_"   )
DEFINE_IDTYPE( 4, IDTYPE_DIALOG     , "Dialog.ID"       , L"Dialog.ID"      , IDS_DIALOG_ID     , L"IDD_"   )
DEFINE_IDTYPE( 5, IDTYPE_STRING     , "String.ID"       , L"String.ID"      , IDS_STRING_ID     , L"IDS_"   )
DEFINE_IDTYPE( 6, IDTYPE_ACCEL      , "Accel.ID"        , L"Accel.ID"       , IDS_ACCEL_ID      , L"IDR_"   )
DEFINE_IDTYPE( 7, IDTYPE_ICON       , "Icon.ID"         , L"Icon.ID"        , IDS_ICON_ID       , L"IDI_"   )
DEFINE_IDTYPE( 8, IDTYPE_ANICURSOR  , "AniCursor.ID"    , L"AniCursor.ID"   , IDS_ANICURSOR_ID  , L"IDR_"   )
DEFINE_IDTYPE( 9, IDTYPE_ANIICON    , "AniIcon.ID"      , L"AniIcon.ID"     , IDS_ANIICON_ID    , L"IDR_"   )
DEFINE_IDTYPE(10, IDTYPE_HTML       , "Html.ID"         , L"Html.ID"        , IDS_HTML_ID       , L"IDR_"   )
DEFINE_IDTYPE(11, IDTYPE_HELP       , "Help.ID"         , L"Help.ID"        , IDS_HELP_ID       , L"HID_"   )
DEFINE_IDTYPE(12, IDTYPE_COMMAND    , "Command.ID"      , L"Command.ID"     , IDS_COMMAND_ID    , L"IDM_"   )
DEFINE_IDTYPE(13, IDTYPE_CONTROL    , "Control.ID"      , L"Control.ID"     , IDS_CONTROL_ID    , L"IDC_"   )
DEFINE_IDTYPE(14, IDTYPE_RESOURCE   , "Resource.ID"     , L"Resource.ID"    , IDS_RESOURCE_ID   , L"IDR_"   )
DEFINE_IDTYPE(15, IDTYPE_MESSAGE    , "Message.ID"      , L"Message.ID"     , IDS_MESSAGE_ID    , L"MSGID_" )
DEFINE_IDTYPE(16, IDTYPE_WINDOW     , "Window.ID"       , L"Window.ID"      , IDS_WINDOW_ID     , L"IDW_"   )
DEFINE_IDTYPE(17, IDTYPE_NEWCOMMAND , "New.Command.ID"  , L"New.Command.ID" , IDS_NEWCOMMAND_ID , L"ID_"    )
DEFINE_IDTYPE(18, IDTYPE_PROMPT     , "Prompt.ID"       , L"Prompt.ID"      , IDS_PROMPT_ID     , L"IDP_"   )
DEFINE_IDTYPE(19, IDTYPE_RCDATA     , "RCData.ID"       , L"RCData.ID"      , IDS_RCDATA_ID     , L"IDR_"   )
DEFINE_IDTYPE(20, IDTYPE_MSGTABLE   , "MsgTable.ID"     , L"MsgTable.ID"    , IDS_MSGTABLE_ID   , L"IDR_"   )
